// src/lib/api.ts (temporary compatibility)
export * from "@/features/auth/api";
export * from "@/features/passenger/api";
export * from "@/features/driver/api";
export * from "@/features/operator/api";
export * from "@/features/gdpr/api";
export * from "@/features/meta/api";
export * from "@/features/geofence/api";
export * from "@/features/stations/api";
export * from "@/features/inspector/api";