INSERT INTO [dbo].[VehicleType] ([VehicleTypeId], [Name]) VALUES
    ('1', 'Sedan'),
    ('2', 'Hatchback'),
    ('3', 'SUV'),
    ('4', 'Coupe'),
    ('5', 'Convertible'),
    ('6', 'Pickup Truck'),
    ('7', 'Minivan'),
    ('8', 'Van'),
    ('9', 'Wagon'),
    ('10', 'Crossover'),
    ('11', 'Luxury Car'),
    ('12', 'Sports Car'),
    ('13', 'Electric Car'),
    ('14', 'Hybrid Car'),
    ('15', 'Truck');
